const cars=[
 {name:'Nexa X8',type:'Sähkö',price:54900,range:'550 km',power:'350 hv',image:'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=900&q=80',desc:'Laatutason sähkö-SUV, jossa yhdistyvät voima, turvallisuus ja huipputeknologia.'},
 {name:'Velo R',type:'Coupé',price:49300,range:'420 km',power:'320 hv',image:'https://images.unsplash.com/photo-1614200187524-dc4b892acf16?auto=format&fit=crop&w=900&q=80',desc:'Fastback-muotoilu, vakaa ajo ja virtaa jokaiseen kaarteeseen.'},
 {name:'Horizon S',type:'Perhe',price:46800,range:'480 km',power:'245 hv',image:'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=900&q=80',desc:'Tilava, turvallinen ja älykäs perheauto, joka tekee arjesta sujuvaa.'},
 {name:'Summit 4',type:'SUV',price:58200,range:'600 km',power:'380 hv',image:'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=900&q=80',desc:'Monipuolinen maastourheilija, joka sopii kaupunkiin ja vaativiin olosuhteisiin.'},
 {name:'Nova E',type:'Sähkö',price:41400,range:'390 km',power:'204 hv',image:'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&w=900&q=80',desc:'Sileä, hiljainen ja tehokas kaupunkimalli modernille elämäntavalle.'},
 {name:'Apex GT',type:'Sport',price:82900,range:'—',power:'640 hv',image:'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=900&q=80',desc:'Suorituskykyä ja ajamisen iloa ilman kompromisseja.'}
];
const euro=n=>new Intl.NumberFormat('fi-FI').format(n)+' €';
function card(car){return `<article class="car-card"><div class="car-image"><img src="${car.image}" alt="${car.name}" loading="lazy"><span class="car-tag">${car.type}</span><button class="heart" aria-label="Lisää suosikkeihin">♡</button></div><div class="car-info"><div class="car-title"><h3>${car.name}</h3><strong>${euro(car.price)}</strong></div><p>${car.desc}</p><div class="specs"><span>↗ ${car.range}</span><span>⚡ ${car.power}</span></div><div class="card-actions"><button class="button button-small button-dark" data-details="${car.name}">Katso tiedot</button><button class="button button-small button-outline" data-add="${car.name}">Varaa koeajo</button></div></div></article>`}
function render(list,target){if(!target)return;target.innerHTML=list.map(card).join('')||'<div class="empty">Hakusi ei tuottanut tuloksia. Kokeile toista hakusanaa.</div>';const count=document.querySelector('#resultCount');if(count)count.textContent=`${list.length} autoa löytyi`}
function cart(){const items=JSON.parse(localStorage.getItem('novaCart')||'[]');document.querySelectorAll('#cartCount').forEach(x=>x.textContent=items.length)}
function initCatalog(){const grid=document.querySelector('#carGrid');if(!grid)return;let filter=new URLSearchParams(location.search).get('type')||'Kaikki';const search=document.querySelector('#searchInput');const sort=document.querySelector('#sortSelect');function update(){let list=cars.filter(c=>(filter==='Kaikki'||c.type===filter)&&(!search.value||`${c.name} ${c.type}`.toLowerCase().includes(search.value.toLowerCase())));if(sort.value==='low')list.sort((a,b)=>a.price-b.price);if(sort.value==='high')list.sort((a,b)=>b.price-a.price);render(list,grid)}document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x===b));update()});search.oninput=update;sort.onchange=update;update()}
function modal(name){const c=cars.find(x=>x.name===name),box=document.querySelector('#modalContent');if(!box)return;box.innerHTML=`<img class="modal-image" src="${c.image}" alt="${c.name}"><p class="eyebrow">${c.type}</p><h2>${c.name}</h2><p>${c.desc}</p><div class="modal-specs"><b>${euro(c.price)}<small>alkaen</small></b><b>${c.range}<small>toimintasäde</small></b><b>${c.power}<small>teho</small></b></div><a class="button button-primary" href="contact.html">Varaa koeajo ↗</a>`;document.querySelector('#carModal').classList.remove('hidden')}
document.addEventListener('click',e=>{const detail=e.target.closest('[data-details]'),add=e.target.closest('[data-add]');if(detail)modal(detail.dataset.details);if(add){const list=JSON.parse(localStorage.getItem('novaCart')||'[]');if(!list.includes(add.dataset.add))list.push(add.dataset.add);localStorage.setItem('novaCart',JSON.stringify(list));cart();add.textContent='Varattu ✓';add.disabled=true}});document.querySelector('#closeModal')?.addEventListener('click',()=>document.querySelector('#carModal').classList.add('hidden'));document.querySelector('#carModal')?.addEventListener('click',e=>{if(e.target.id==='carModal')e.target.classList.add('hidden')});
const featured=document.querySelector('#featuredCars');if(featured)render(cars.slice(0,3),featured);initCatalog();cart();document.querySelector('#contactForm')?.addEventListener('submit',e=>{e.preventDefault();document.querySelector('#formMessage').textContent='Kiitos! Pyyntösi vastaanotettiin. Olemme sinuun yhteydessä pian.';e.target.reset()});